//
//  NoteFieldModel.swift
//
//  Generated by Notenik on 2020-08-10
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

final class NoteFieldModel: Model {
    
    static let schema: String = "note_fields"
    
    struct FieldKeys {
        static var label: FieldKey { "label" }
        static var value: FieldKey { "value" }
		static var noteId: FieldKey { "note_id" }
    }

    @ID() var id: UUID?
    @Field(key: FieldKeys.label) var label: String
    @Field(key: FieldKeys.value) var value: String
    @Parent(key: FieldKeys.noteId) var note: NoteModel

	init() { }
    
    init(id: UUID? = nil,
    	label: String, 
    	value: String, 
		noteId: UUID) 
	{
		self.id = id
    	self.label = label
    	self.value = value
		self.$note.id = noteId
	} 
}
