//
//  UserModel.swift
//
//  Generated by Notenik on 2020-08-11
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

final class UserModel: Model {
    
    static let schema: String = "users"
    
    struct FieldKeys {
        static var userId: FieldKey { "user_id" }
        static var email: FieldKey { "email" }
        static var password: FieldKey { "password" }
        static var firstName: FieldKey { "first_name" }
        static var fullName: FieldKey { "full_name" }
    }

    @ID() var id: UUID?
    @Field(key: FieldKeys.userId) var userId: String
    @Field(key: FieldKeys.email) var email: String
    @Field(key: FieldKeys.password) var password: String
    @Field(key: FieldKeys.firstName) var firstName: String
    @Field(key: FieldKeys.fullName) var fullName: String

    init() { }
    
    init(id: UUID? = nil,
        userId: String,
        email: String,
        password: String,
        firstName: String,
        fullName: String)
    {
        self.id = id
        self.userId = userId
        self.email = email
        self.password = password
        self.firstName = firstName
        self.fullName = fullName
    }
}

extension UserModel: Authenticatable {

}

extension UserModel: SessionAuthenticatable {
    typealias SessionID = UUID
    
    var sessionID: SessionID {
        self.id!
    }
}
