//
//  NoteMigrationSeed.swift
//
//  Generated by Notenik on 2020-08-10
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

struct NoteMigrationSeed: Migration {

    func prepare(on db: Database) -> EventLoopFuture<Void> {
        db.eventLoop.flatten([ ])
        .flatMap {
            self.notes().create(on: db) 
            self.noteFields().create(on: db)
        }
    }

    func revert(on db: Database) -> EventLoopFuture<Void> {
        db.eventLoop.flatten([
            NoteModel.query(on: db).delete(),
            NoteFieldModel.query(on: db).delete(),
        ])
    }

}
