//
//  UserMigrationSeed.swift
//
//  Generated by Notenik on 2020-08-10
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

struct UserMigrationSeed: Migration {

	private func users() -> [UserModel] {
        [
            UserModel(userId: "hbowie@notenik.net", 
    			email: "hbowie@hey.com", 
    			password: try! Bcrypt.hash("ChangeMe1"), 
    			firstName: "Herb", 
    			fullName: "Herb Bowie")
        ]
    }

    func prepare(on db: Database) -> EventLoopFuture<Void> {
        db.eventLoop.flatten([ ])
        .flatMap {
            self.users().create(on: db) 
		}
    }

    func revert(on db: Database) -> EventLoopFuture<Void> {
        db.eventLoop.flatten([
            UserModel.query(on: db).delete(),
        ])
    }

}
